//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_HD_DATA_SHARING_SCHEMA_H
#define PXR_IMAGING_HD_DATA_SHARING_SCHEMA_H

/// \file

#include "pxr/imaging/hd/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define HD_DATA_SHARING_SCHEMA_TOKENS \
    (dataSharing) \
    (sharingId) \

TF_DECLARE_PUBLIC_TOKENS(HdDataSharingSchemaTokens, HD_API,
    HD_DATA_SHARING_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


/// \class HdDataSharingSchema
///
class HdDataSharingSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    HdDataSharingSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "dataSharing" from the parent container and constructs a
    /// HdDataSharingSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    HD_API
    static HdDataSharingSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
    /// Wraps an SdfPath so that it is not affected by the
    /// prefixing scene index.
    class SharingId {
    public:
        SharingId(const SdfPath &path)
         : _path(path)
        {
        }

        const SdfPath &GetPath() const { return _path; }

        bool operator==(const SharingId &other) const {
            return _path == other._path;
        }

    private:
        HD_API
        friend std::ostream &operator <<(std::ostream &stream,
                                         SharingId const &p);

        SdfPath _path;
    };

    using SharingIdDataSource = HdTypedSampledDataSource<SharingId>;

    /// Extracts SdfPath from container that was added via
    /// SharingIdDataSource.
    HD_API SdfPath GetSharingId() const;

// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{ 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    HD_API
    static const TfToken &GetSchemaToken();

    /// @} 

    /// \name Schema construction
    /// @{
    HD_API
    static HdContainerDataSourceHandle
    BuildRetained(
        size_t count,
        const TfToken *names,
        const HdDataSourceBaseHandle *values);

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif