//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/dataSharingSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdDataSharingSchemaTokens,
    HD_DATA_SHARING_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--

SdfPath
HdDataSharingSchema::GetSharingId() const
{
    if (!_container) {
        return SdfPath();
    }
    SharingIdDataSource::Handle const ds =
        SharingIdDataSource::Cast(_container->Get(
            HdDataSharingSchemaTokens->sharingId));
    if (!ds) {
        return SdfPath();
    }
    return ds->GetTypedValue(0.0f).GetPath();
}

std::ostream &
operator <<(std::ostream &stream, HdDataSharingSchema::SharingId const &p)
{
    return stream << "HdDataSharingSchema::SharingId(" << p.GetPath() << ")";
}

// --(END CUSTOM CODE: Schema Methods)--

/*static*/
HdContainerDataSourceHandle
HdDataSharingSchema::BuildRetained(
    const size_t count,
    const TfToken * const names,
    const HdDataSourceBaseHandle * const values)
{
    return HdRetainedContainerDataSource::New(count, names, values);
}

/*static*/
HdDataSharingSchema
HdDataSharingSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdDataSharingSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdDataSharingSchemaTokens->dataSharing))
        : nullptr);
}

/*static*/
const TfToken &
HdDataSharingSchema::GetSchemaToken()
{
    return HdDataSharingSchemaTokens->dataSharing;
} 

PXR_NAMESPACE_CLOSE_SCOPE